### ISSUE TITLE
Issue when a try to execute npm start

### ISSUE THREAD

**Issue by luenmuvel** [MadnessLabs/enjin-components#5]
**Stencil version:** 
```
@stencil/core@1.7.5
```

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I making all steps from the README.md but when I try to execute `npm start` I get the next error:
```
[55:00.1]  type checking finished in 10.23 s

[ ERROR ]  TypeScript: node_modules/@stencil/core/dist/declarations/testing.d.ts:4:19
           All declarations of 'Matchers' must have identical type parameters.

      L3:  namespace jest {
      L4:      interface Matchers<R, T> {
      L5:          /**

[ ERROR ]  TypeScript: node_modules/@types/jest/index.d.ts:531:31
           Generic type 'Matchers<R, T>' requires 2 type argument(s).

    L530:   */
    L531:  <T = any>(actual: T): Matchers<T>;
    L532:  /**

[ ERROR ]  TypeScript: node_modules/@types/jest/index.d.ts:606:15
           All declarations of 'Matchers' must have identical type parameters.

    L606:      interface Matchers<R> {
    L607:          /**

[55:00.1]  build failed in 13.03 s
```

**Steps to reproduce:**
git clone https://github.com/ionic-team/stencil-component-starter.git my-component
cd my-component
git remote rm origin
npm install
npm start

**Comment by popcorn245** [comment]
@luenmuvel Hey sorry for the slow reply on this.  Thanks to a pull-request by @ofhouse you should be able to do the npm install now.  I am going to push out a couple more updates to get everything back up to date now. Thanks for submitting an issue and I can promise next time won't have the same delay. Happy coding! ^_^
